name: patchai_flutter_modules_cli
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.6.0
  io: ^0.3.4
  mason: ^0.0.1-dev.26
  meta: ^1.2.4
  path: ^1.7.0
  usage: ^3.4.2

dev_dependencies:
  build_runner: ^1.10.0
  build_verify: ^1.1.1
  build_version: ^2.0.1
  pedantic: ^1.9.2

